### ISSUE TITLE
adapt-setup is downloading previous release of hotgrid.

### ISSUE THREAD

**Issue by joe-replin** [cgkineo/adapt-gulp-cli#10]
It is downloading v3.2.0 of adapt-hotgrid. The expected result would be to download v4.0.0.

**Comment by tomgreenfield** [comment]
Hi @joe-replin, adapt-setup doesn't actually do any downloading, it just palms off to Adapt CLI.

Suggest this issue is moved to Hotgrid; it probably needs tagging.

**Comment by moloko** [comment]
Indeed, at the time of writing there is no v4.0.0 release of hotgrid - the [most recent release is v3.2.0](https://github.com/cgkineo/adapt-hotgrid/releases). 

v4 will be released soon though.
