### ISSUE TITLE
Core being added to components folder

### ISSUE THREAD

**Issue by tomallpress** [cgkineo/adapt-gulp-cli#16]
When running adapt-setup create, i selected the plugins i needed to install, one of which was the core plugin. when i finished the process and the plugins were installed, Core had been installed into the components folder.

**Comment by oliverfoster** [comment]
The core plugin is installed into the src/core folder as part of the `npm install` command. [adapt-contrib-core](https://github.com/adaptlearning/adapt-contrib-core) should not be install via adapt-setup.
