### ISSUE TITLE
can we avoid having two copies of all the content assets?

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-gulp-cli#3]
I can't think of any good reason why we really need to have a copy of course media (images, video, audio, PDFs etc) in both src and build. 

It seems to be down to it being the way the original Adapt OS build grunt task worked. 

Having two copies of all these files taking up tons of disk space both on the SVN server, on people's PC and is using up loads of bandwidth - not to mention being error-prone as we still do get instances of people updating content graphics/video in the build but not in the src folder.

If there's any possibility of using the switchover to gulp to eliminate this redundancy, I'd really like to explore it.

**Comment by tomgreenfield** [comment]
This is a fantastic idea for discussion – however this issue should probably be moved to [adapt-builder](https://github.com/cgkineo/adapt-builder).

**Comment by oliverfoster** [comment]
no 'courses' in the 'src' folder? just 'build/[courseName]/course' instead?

**Comment by moloko** [comment]
hmm, it's certainly a thought. it's much closer to the process (which works well) we use for Papaya where all content goes straight into the build folder.

the only reason I can think not to do this would be that we would be able to 'uglify' the JSON - unless we went ahead with the plan to have a export-to-zip feature, it could uglify at that point.

Unless anyone can think of a reason why we shouldn't do this, I say let's go for it

**Comment by tomgreenfield** [comment]
Tool updated in 72b9a3c28250b518453944aa90c419f95a2ea9b4 to install courses directly into the builds folder.
