### ISSUE TITLE
Add Kineo's OS plugins to this tool

### ISSUE THREAD

**Issue by simondate** [cgkineo/adapt-gulp-cli#5]
Since this is a Kineo owned tool could we extend it to also install Kineo's open source plugins?

It currently uses https://github.com/tomgreenfield/adapt-inspector. So it clearly isn't just a AdaptLearning only tool.

**Comment by simondate** [comment]
# Plugins to add

## cgkineo

### components
- [x] https://github.com/cgkineo/adapt-hotgrid
- [x] https://github.com/cgkineo/adapt-narrativeStrip
- [x] https://github.com/cgkineo/adapt-tabs

### extensions
- [x] https://github.com/cgkineo/adapt-quicknav
- [x] https://github.com/cgkineo/adapt-close
- [x] https://github.com/cgkineo/adapt-devtools
- [x] https://github.com/cgkineo/adapt-search
- [x] https://github.com/cgkineo/adapt-article-reveal

### menu
- [x] https://github.com/cgkineo/adapt-hotspot-menu
- [ ] https://github.com/cgkineo/adapt-cover-menu

## adaptlearning

### components
- [x] https://github.com/adaptlearning/adapt-contrib-confidenceSlider
- [ ] ~~https://github.com/adaptlearning/adapt-contrib-linkedConfidenceSlider~~

**Comment by simondate** [comment]
Discussed with @tomgreenfield and we have identified what make sense to add.

**Comment by tomgreenfield** [comment]
The suggested plugins have now been added.

Leaving Cover Menu and the Confidence Sliders until bugs are ironed out and major PRs have been merged.

**Comment by moloko** [comment]
confidenceSlider should now be OK to go in; have removed linkedConfidenceSlider since it no longer exists

**Comment by moloko** [comment]
can this now be closed?

**Comment by simondate** [comment]
I don't use this anymore. Maybe you should ask your production team to see if they find it useful?
