### ISSUE TITLE
adapt-setup install

### ISSUE THREAD

**Issue by tomallpress** [cgkineo/adapt-gulp-cli#9]
When i run `adapt-setup install` within an already set up dev folder (because i want to retroactively install something to the dev folder), it's giving me a message that says:

> The framework will be downloaded to your current directory. Do you wish to continue?

i don't want to download the framework as that's already in there; when i hit 'no' the command stops, so i can't select any functionality to install.

**Comment by tomgreenfield** [comment]
Hi Tom, that functionality has been superceded by the [official CLI](https://github.com/adaptlearning/adapt-cli), which implements thorough version checking amongst other things:

```console
adapt install <plugin>
```

And if you need to look up the plugin name beforehand:
```console
adapt search <plugin>
```
